In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler


In [2]:
data=load_breast_cancer()

In [3]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
data['DESCR']

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For inst

In [6]:
print(data['DESCR'])

#569 tumors each having 30 attributes

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [7]:
print(data['frame'])

None


In [8]:
print(data['target_names'])

['malignant' 'benign']


In [9]:
print(data['target'])

# 0=malignant  (cancerous)
# 1=benign     (non - cancerous)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [10]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [11]:
print(data['data'][0])      #values of first tumor

[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]


In [12]:
data['data'].shape


# 569 tumors each having 30 features.
# Each tumor has a target , either 0 or 1. Means if any tumor has target=0,it is malignant and if any tumor has target=1,it is benign

(569, 30)

In [13]:
print(data['feature_names'])
print(len(data['feature_names']))

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
30


In [14]:
j = 0
for i in data['feature_names']:
  print(i,":",data['data'][568][j])
  j+=1

#values and features of 568th tumor

mean radius : 7.76
mean texture : 24.54
mean perimeter : 47.92
mean area : 181.0
mean smoothness : 0.05263
mean compactness : 0.04362
mean concavity : 0.0
mean concave points : 0.0
mean symmetry : 0.1587
mean fractal dimension : 0.05884
radius error : 0.3857
texture error : 1.428
perimeter error : 2.548
area error : 19.15
smoothness error : 0.007189
compactness error : 0.00466
concavity error : 0.0
concave points error : 0.0
symmetry error : 0.02676
fractal dimension error : 0.002783
worst radius : 9.456
worst texture : 30.37
worst perimeter : 59.16
worst area : 268.6
worst smoothness : 0.08996
worst compactness : 0.06444
worst concavity : 0.0
worst concave points : 0.0
worst symmetry : 0.2871
worst fractal dimension : 0.07039


In [15]:
feature=data['data']
feature

#attributes of each tumor

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [16]:
label=data['target']
label

# target or label =  malignant or benign

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [17]:
feature.shape

(569, 30)

In [18]:
label.shape

(569,)

In [19]:
print(data['DESCR'])

# here if we observe that min and max values are very much varied, some have small range and some have a very wide range 

# As for area attribute, range is very high , but if we look for  concave points , range is very small

# So we need to rearrange all the values in a particular range, so that every row is having only a particular range

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [20]:
# Standardising the data

scale = StandardScaler()

feature = scale.fit_transform(feature)
print(feature)

[[ 1.09706398 -2.07333501  1.26993369 ...  2.29607613  2.75062224
   1.93701461]
 [ 1.82982061 -0.35363241  1.68595471 ...  1.0870843  -0.24388967
   0.28118999]
 [ 1.57988811  0.45618695  1.56650313 ...  1.95500035  1.152255
   0.20139121]
 ...
 [ 0.70228425  2.0455738   0.67267578 ...  0.41406869 -1.10454895
  -0.31840916]
 [ 1.83834103  2.33645719  1.98252415 ...  2.28998549  1.91908301
   2.21963528]
 [-1.80840125  1.22179204 -1.81438851 ... -1.74506282 -0.04813821
  -0.75120669]]


In [21]:
# Comparing before and after standardisation
# For first tumor

j = 0
for i in data['feature_names']:
  print(i,":",data['data'][568][j])
  j+=1

    
print('------------------------AFTER-----------------------------------------')

j = 0
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

    

mean radius : 7.76
mean texture : 24.54
mean perimeter : 47.92
mean area : 181.0
mean smoothness : 0.05263
mean compactness : 0.04362
mean concavity : 0.0
mean concave points : 0.0
mean symmetry : 0.1587
mean fractal dimension : 0.05884
radius error : 0.3857
texture error : 1.428
perimeter error : 2.548
area error : 19.15
smoothness error : 0.007189
compactness error : 0.00466
concavity error : 0.0
concave points error : 0.0
symmetry error : 0.02676
fractal dimension error : 0.002783
worst radius : 9.456
worst texture : 30.37
worst perimeter : 59.16
worst area : 268.6
worst smoothness : 0.08996
worst compactness : 0.06444
worst concavity : 0.0
worst concave points : 0.0
worst symmetry : 0.2871
worst fractal dimension : 0.07039
------------------------AFTER-----------------------------------------
mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.

In [22]:
# We will pass these features to the neural network and will get '0' or '1' as output

In [23]:
print(feature[568])
print(data['target_names'][label[568]],label[568])

[-1.80840125  1.22179204 -1.81438851 -1.34778924 -3.11208479 -1.15075248
 -1.11487284 -1.26181958 -0.8200699  -0.56103238 -0.07027874  0.3830925
 -0.15744905 -0.46615196  0.04934236 -1.16351619 -1.05750068 -1.91344745
  0.75282996 -0.382754   -1.41089258  0.76418957 -1.43273495 -1.07581292
 -1.85901852 -1.2075525  -1.30583065 -1.74506282 -0.04813821 -0.75120669]
benign 1


In [24]:
df= pd.DataFrame(feature,columns=data['feature_names'])

In [25]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0       1.097064     -2.073335        1.269934   0.984375         1.568466   
1       1.829821     -0.353632        1.685955   1.908708        -0.826962   
2       1.579888      0.456187        1.566503   1.558884         0.942210   
3      -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4       1.750297     -1.151816        1.776573   1.826229         0.280372   
..           ...           ...             ...        ...              ...   
564     2.110995      0.721473        2.060786   2.343856         1.041842   
565     1.704854      2.085134        1.615931   1.723842         0.102458   
566     0.702284      2.045574        0.672676   0.577953        -0.840484   
567     1.838341      2.336457        1.982524   1.735218         1.525767   
568    -1.808401      1.221792       -1.814389  -1.347789        -3.112085   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            3.283515        2.652874             2.532475       2.217515   
1           -0.487072       -0.023846             0.548144       0.001392   
2            1.052926        1.363478             2.037231       0.939685   
3            3.402909        1.915897             1.451707       2.867383   
4            0.539340        1.371011             1.428493      -0.009560   
..                ...             ...                  ...            ...   
564          0.219060        1.947285             2.320965      -0.312589   
565         -0.017833        0.693043             1.263669      -0.217664   
566         -0.038680        0.046588             0.105777      -0.809117   
567          3.272144        3.296944             2.658866       2.137194   
568         -1.150752       -1.114873            -1.261820      -0.820070   

     mean fractal dimension  ...  worst radius  worst texture  \
0                  2.255747  ...      1.886690      -1.359293   
1                 -0.868652  ...      1.805927      -0.369203   
2                 -0.398008  ...      1.511870      -0.023974   
3                  4.910919  ...     -0.281464       0.133984   
4                 -0.562450  ...      1.298575      -1.466770   
..                      ...  ...           ...            ...   
564               -0.931027  ...      1.901185       0.117700   
565               -1.058611  ...      1.536720       2.047399   
566               -0.895587  ...      0.561361       1.374854   
567                1.043695  ...      1.961239       2.237926   
568               -0.561032  ...     -1.410893       0.764190   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0           2.303601    2.001237          1.307686           2.616665   
1           1.535126    1.890489         -0.375612          -0.430444   
2           1.347475    1.456285          0.527407           1.082932   
3          -0.249939   -0.550021          3.394275           3.893397   
4           1.338539    1.220724          0.220556          -0.313395   
..               ...         ...               ...                ...   
564         1.752563    2.015301          0.378365          -0.273318   
565         1.421940    1.494959         -0.691230          -0.394820   
566         0.579001    0.427906         -0.809587           0.350735   
567         2.303601    1.653171          1.430427           3.904848   
568        -1.432735   -1.075813         -1.859019          -1.207552   

     worst concavity  worst concave points  worst symmetry  \
0           2.109526              2.296076        2.750622   
1          -0.146749              1.087084       -0.243890   
2           0.854974              1.955000        1.152255   
3           1.989588              2.175786        6.046041   
4           0.613179              0.729259       -0.868353   
..               ...                   ...             ...   
564         0.664512              1.629151       -1

In [26]:

df_features= pd.DataFrame(feature , columns = data['feature_names'])
df_label = pd.DataFrame(label , columns = ['label'])
df = pd.concat([df_features, df_label], axis=1)

df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0       1.097064     -2.073335        1.269934   0.984375         1.568466   
1       1.829821     -0.353632        1.685955   1.908708        -0.826962   
2       1.579888      0.456187        1.566503   1.558884         0.942210   
3      -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4       1.750297     -1.151816        1.776573   1.826229         0.280372   
..           ...           ...             ...        ...              ...   
564     2.110995      0.721473        2.060786   2.343856         1.041842   
565     1.704854      2.085134        1.615931   1.723842         0.102458   
566     0.702284      2.045574        0.672676   0.577953        -0.840484   
567     1.838341      2.336457        1.982524   1.735218         1.525767   
568    -1.808401      1.221792       -1.814389  -1.347789        -3.112085   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0            3.283515        2.652874             2.532475       2.217515   
1           -0.487072       -0.023846             0.548144       0.001392   
2            1.052926        1.363478             2.037231       0.939685   
3            3.402909        1.915897             1.451707       2.867383   
4            0.539340        1.371011             1.428493      -0.009560   
..                ...             ...                  ...            ...   
564          0.219060        1.947285             2.320965      -0.312589   
565         -0.017833        0.693043             1.263669      -0.217664   
566         -0.038680        0.046588             0.105777      -0.809117   
567          3.272144        3.296944             2.658866       2.137194   
568         -1.150752       -1.114873            -1.261820      -0.820070   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                  2.255747  ...      -1.359293         2.303601    2.001237   
1                 -0.868652  ...      -0.369203         1.535126    1.890489   
2                 -0.398008  ...      -0.023974         1.347475    1.456285   
3                  4.910919  ...       0.133984        -0.249939   -0.550021   
4                 -0.562450  ...      -1.466770         1.338539    1.220724   
..                      ...  ...            ...              ...         ...   
564               -0.931027  ...       0.117700         1.752563    2.015301   
565               -1.058611  ...       2.047399         1.421940    1.494959   
566               -0.895587  ...       1.374854         0.579001    0.427906   
567                1.043695  ...       2.237926         2.303601    1.653171   
568               -0.561032  ...       0.764190        -1.432735   -1.075813   

     worst smoothness  worst compactness  worst concavity  \
0            1.307686           2.616665         2.109526   
1           -0.375612          -0.430444        -0.146749   
2            0.527407           1.082932         0.854974   
3            3.394275           3.893397         1.989588   
4            0.220556          -0.313395         0.613179   
..                ...                ...              ...   
564          0.378365          -0.273318         0.664512   
565         -0.691230          -0.394820         0.236573   
566         -0.809587           0.350735         0.326767   
567          1.430427           3.904848         3.197605   
568         -1.859019          -1.207552        -1.305831   

     worst concave points  worst symmetry  worst fractal dimension  label  
0                2.296076        2.750622                 1.937015      0  
1                1.087084       -0.243890                 0.281190      0  
2                1.955000        1.152255                 0.201391      0  
3                2.175786        6.046041                 4.935010      0  
4                0.729259       -0.868353                -0.397100   

In [27]:

#500 Training
X_train = feature[:500]
y_train = label[:500]

#35 Validation
X_val = feature[500:535]
y_val = label[500:535]

#34 Testing
X_test = feature[535:]
y_test = label[535:]

In [28]:
# neural network

from keras.models import Sequential
from keras.layers import Dense

In [49]:
model=Sequential()

model.add(Dense(15, activation='relu',input_dim=30))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [53]:
model.fit(X_train,y_train,batch_size=1,epochs=5,validation_data=(X_val,y_val))

Epoch 1/5
500/500 [==============================] - 3s 6ms/step - loss: 0.0700 - accuracy: 0.9800 - val_loss: 0.0385 - val_accuracy: 1.0000
Epoch 2/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0538 - accuracy: 0.9880 - val_loss: 0.0422 - val_accuracy: 1.0000
Epoch 3/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0478 - accuracy: 0.9880 - val_loss: 0.0464 - val_accuracy: 0.9714
Epoch 4/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0441 - accuracy: 0.9880 - val_loss: 0.0455 - val_accuracy: 0.9714
Epoch 5/5
500/500 [==============================] - 2s 4ms/step - loss: 0.0395 - accuracy: 0.9900 - val_loss: 0.0367 - val_accuracy: 0.9714


In [54]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 8ms/step - loss: 0.0571 - accuracy: 0.9412


[0.057147011160850525, 0.9411764740943909]

In [55]:
#Predictions
sample=X_test[0]

In [56]:
sample

array([ 1.82414032,  0.36543133,  1.88778669,  1.85751441,  0.58638323,
        1.31824626,  1.50283863,  2.14814488,  1.15143953, -0.04077169,
        1.05904307, -0.4114087 ,  0.910827  ,  1.04382537, -0.82102626,
        0.03810891,  0.27043808,  0.3915519 , -0.12862155, -0.41830962,
        1.66304049, -0.03211657,  1.57682617,  1.63207582, -0.24410428,
        0.37681708,  0.82091153,  1.5256103 ,  0.28512459, -0.45750286])

In [58]:
sample.shape


(30,)

In [62]:
import numpy as np

sample=np.reshape(sample, (1,30))
sample.shape

(1, 30)

In [68]:
model.predict(sample)[0][0]

1.3482485e-09

In [69]:
if model.predict(sample)[0][0]>0.5:
    print("Benign")
else:
    print("Malignant")

Malignant


In [76]:
print("-------------Predicted vs actual value---------------")
for i in range(100):
    sample=X_test[i]
    sample=np.reshape(sample, (1,30))
    
    if model.predict(sample)[0][0]>0.5:
        print("-Benign")
    else:
        print("-Malignant")
        
    if y_test[i]==0:
        print("*Malignant")
    else:
        print("*Benign")
        
    print("----------------------------")

-------------Predicted vs actual value---------------
-Malignant
*Malignant
----------------------------
-Malignant
*Malignant
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Malignant
*Benign
----------------------------
-Malignant
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
----------------------------
-Benign
*Benign
------------

IndexError: index 34 is out of bounds for axis 0 with size 34

In [ ]:
#df=df.sample(frac=1) to shuffle the dataset