In [6]:
import numpy as np

In [7]:
lst=[1,2,3]

In [8]:
type(lst)

list

In [9]:
#To convert list into numpy array
np_array=np.array(lst)

In [10]:
np_array

array([1, 2, 3])

In [11]:
type(np_array)

numpy.ndarray

In [15]:
#multi-dimensional list into numpy array
lst1= [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
lst1

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [16]:
np_array1=np.array(lst1)
np_array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
np_array1.shape

(3, 4)

In [20]:
#changing the shape

np_array1=np.reshape(np_array1,(4,3))
np_array1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
np_array1.shape

(4, 3)

In [23]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.zeros((4,3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((4,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Random number generation

In [30]:
random=np.random.randint(0,9)
random

7

In [34]:
#generating a number between 0-100
random=np.random.randint(0,101)
random

61

In [38]:
# to print 5 numbers between 2 to 10
np.linspace(2,10,5)       

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
# to print 7 numbers between 2 to 10
np.linspace(2,10,7)       

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [40]:
np.mean(np.linspace(2,10,7))

6.0

In [41]:
np.sqrt(np.linspace(2,10,7))

array([1.41421356, 1.82574186, 2.1602469 , 2.44948974, 2.7080128 ,
       2.94392029, 3.16227766])

In [46]:
array=np.linspace(2,10,7)
array

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [47]:
array+2

array([ 4.        ,  5.33333333,  6.66666667,  8.        ,  9.33333333,
       10.66666667, 12.        ])

In [48]:
array-2

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [49]:
array*2

array([ 4.        ,  6.66666667,  9.33333333, 12.        , 14.66666667,
       17.33333333, 20.        ])

In [50]:
array/2

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])